### ISSUE TITLE
Missing github URL for cryptoauthlib

### ISSUE THREAD

**Issue by carldunham** [MicrochipTech/cryptoauth-openssl-engine#1]
The file engine_atecc/cryptoauthlib/README.md contains instructions for adding cryptoauthlib as a submodule, but only refers to the repo URL as `<giturl to CryptoAuthLib>`. What should the actual URL be? The version here (and in MongooseOS) is clearly far newer than the one available at the Microchip/Atmel website.

Thanks!

**Comment by bryan-hunt** [comment]
There is not an external repo for CryptoAuthLib. The current release policy has it available as a package download from Microchip http://www.microchip.com/SWLibraryWeb/product.aspx?product=CryptoAuthLib

Release 2 has just been released with numerous improvements.

The version here should not be considered an official mirror as it is out of date, but different than the mainline release. The versions will be brought in line in the future.
