### ISSUE TITLE
location cryptoauthlib repo

### ISSUE THREAD

**Issue by adriankueng** [MicrochipTech/cryptoauth-openssl-engine#2]
Hi, I'm currently using cryptauthlib from atmel. Is there a repo dedicated to cryptauthlib which is open for everyone?

**Comment by agostrer** [comment]
Hi Adrian,

This library is under the
https://github.com/AtmelCSO/cryptoauth-openssl-engine tree; just follow
this link:
https://github.com/AtmelCSO/cryptoauth-openssl-engine/tree/master/engine_atecc/cryptoauthlib

Regards,
Alex Gostrer

**Comment by daniel-cesarini-tridonic-com** [comment]
Hello Alex,

Does that mean that there is no separate dedicated repository for the cryptoauthlib? Is this to be considered the official and master cryptoauthlib repository?

Thank you,
Daniel.

@adriankueng @agostrer 
FYI: @markus-becker-tridonic-com

**Comment by agostrer** [comment]
Hi Daniel,

You can try to talk to Microchip customer support (Atmel was acquired by Microchip). They should have an internal repository for this library. It was free in the past. And their repository should be the master one. 
But if you are looking for an external source then this is the only one as far as I know. 

Regards,
Alex

**Comment by vgottardi** [comment]
The official source is here http://www.atmel.com/tools/cryptoauthlib.aspx
Mostly the same source as the one in this repository. Only a download, not a git repository.

**Comment by daniel-cesarini-tridonic-com** [comment]
Thank you. I will follow on that. 
In case of news I will report back here.

**Comment by bryan-hunt** [comment]
And it is now available on github: https://github.com/MicrochipTech/cryptoauthlib
