### ISSUE TITLE
Compatibility with ATECC608A

### ISSUE THREAD

**Issue by ghost** [MicrochipTech/cryptoauth-openssl-engine#22]
Is this engine working with ATECC608A device or  any problems can occur with this crypto device?

Thank you!

**Comment by RobertDeRose** [comment]
Almost 3 years later... sadly no response

**Comment by bryan-hunt** [comment]
@RobertDeRose There is a large deprecation notice with a link to the modern implementation on the front page of the repo.

**Comment by RobertDeRose** [comment]
@bryan-hunt Sure there is... but I can't say it's big, but that's because of the new Github redesign.  thanks for pointing out the new repo
