### ISSUE TITLE
How to generate key file

### ISSUE THREAD

**Issue by jimpnet** [MicrochipTech/cryptoauth-openssl-engine#6]
How can I generate the key file for the private key in the atecc08 without destroying it if the slot containing the private key is not locked?

**Comment by jimpnet** [comment]
Also, this is being done at runtime so I can't enter a passphrase.

**Comment by agostrer** [comment]
Hi Jim,

Sorry for the delay, I am on vacation. There is a way to remove the passphrase from a real private key in openssl. Just use it with this fake key.
I think there is a way to create a new key file without regenerating the key in the hardware. But I do not remember;(. I can try to look for it but it will be after July 15th. For now try to check examples. Let me know if you'll still have this problem - I will search for the solution (once I am back to the office). 

Regards,
Alex

**Comment by jimpnet** [comment]
Thanks a lot Alex. I got things working well enough for my needs.

Jim McClure
Staff Software Engineer

<http://www.insightuserconference.com>

4400 Baker Road, Minnetonka, MN 55343
TOLL FREE 888.346.3486 xXXX | FAX 952.908.6129

www.peoplenetonline.com

**Comment by agostrer** [comment]
Great. I am back to the town. Let me know if you have more questions. 

Regards,
Alex
